apiVersion: v1
kind: Service
metadata:
  name: nowlens-frontend
  namespace: nowlens
  labels:
    app.kubernetes.io/name: nowlens
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nowlens
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
